default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:3.7-buster

stages:
  - bootstrap_networking
  - cleanup
  - bootstrap
  - pre_deploy
  - deploy
  - post_deploy
  - test

.base_setup:
  tags:
    - docker-runner

before_script:
  # Setup and add SSH_PRIVATE_KEY to ssh agent
  - 'which ssh-agent || ( apt-get update -qqy && apt-get install openssh-client -qqy )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

bootstrap_networking:
  stage: bootstrap_networking
  extends:
    - .base_setup
  script:
    # Configure the networking and bridge for openstack.
    - python3 deploy.py bootstrap_networking

cleanup:
  stage: cleanup
  extends:
    - .base_setup
  script:
    # Prepare a clean environment - cleanup servers to be used for deploy
    # Ensure there is no ceph and openstack deployment on the servers
    # Restart the nodes to complete the cleanup
    # Verify that the servers are up and online.
    - python3 deploy.py cleanup
 
bootstrap:openstack:
  stage: bootstrap
  extends:
    - .base_setup
  script:
    # Run bootstrap across the servers for installing the pre-reqs for openstack
    - python3 deploy.py bootstrap_openstack

ceph:deploy:
  stage: pre_deploy
  extends:
    - .base_setup
  script:
    # Run bootstrap across the servers for installing the pre-reqs for CEPH
    - python3 deploy.py bootstrap_ceph
    # Deploy ceph on target servers using cephadm
    # Configure kolla options for ceph
    - python3 deploy.py deploy_ceph

openstack:pull:
  stage: pre_deploy
  extends:
    - .base_setup
  script:
    # Pull openstack kolla images
    - python3 deploy.py pre_deploy_openstack

deploy:openstack:
  stage: deploy
  extends:
    - .base_setup
  script:
    # Deploy openstack on target servers using kolla
    # 1. Run Kolla pre-setup
    # 2. Run Kolla deploy
    - python3 deploy.py deploy_openstack

post_deploy:openstack:
  stage: post_deploy
  extends:
    - .base_setup
  script:
    # Setup the openstack cloud with public network, images, flavors etc.
    - python3 deploy.py post_deploy_openstack

test:
  stage: test
  extends:
    - .base_setup
  script:
    # Run refstack tests to ensure that the openstack deploy on target servers is functional
    - python3 deploy.py test_setup
    - python3 deploy.py test_refstack
    - python3 deploy.py test_stress
  #artifacts:
  #  paths:
  #    - /home/ubuntu/refstack-client/.tempest/.stestr/0.json
  #    - /home/ubuntu/refstack-client/.tempest/.stestr/0
