os: linux
dist: bionic
arch: amd64
before_install:
    - sudo apt-get update
    - sudo apt-get install -y ssh qemu-system-x86 qemu-utils cpu-checker
    #- sudo usermod -aG kvm $(whoami)
    - gpasswd -a $(whoami) kvm
    - sudo modprobe kvm_intel
language: python
python:
    - "3.6"
install:
    - pip install transient

stages:
    - pre-deploy
    - deploy
    - post-deploy

jobs:
    include:
        - stage: pre-deploy
          script:
              - lsmod |grep kvm
              - pip list |grep trans
              - sudo ifconfig -a
              - sudo ip addr
              - cat /etc/issue
              - uname -a
              - hostname
              - hostname -i
              - lsmod |grep kvm
              - ls -l /dev/kvm
              - pip list |grep trans
              - kvm-ok
              - sudo kvm-ok
              - id
              - groups
              - sudo transient run -ssh-console -image centos/7:2004.01 -- -enable-kvm -m 1G <<< "uname -a"
              #- sg kvm -c transient run -ssh-console -image centos/7:2004.01 -- -enable-kvm -m 1G <<EOS
              #  "uname -a"
              # EOS
#        - stage: deploy
#          script:
#              - lsmod |grep kvm
#              - ls -l /dev/kvm
#              - pip list |grep trans
#              - transient run -ssh-console -image centos/7:2004.01 -- -enable-kvm -m 1G <<< "uname -a"
