os: linux
dist: bionic
arch: amd64
language: python
python:
    - "3.6"
before_install:
    - sudo apt-get update
install:
    - id
    - groups
jobs:
  include:
    - stage: "Deploy MaaS"
      script:
      - source all_in_one_maas_vm_deployment.sh
    - stage: "Deploy OpenStack"
      script:
      - ip r # | grep src | awk '{print $NF}'
      - ip a
      - ip a | grep "inet " | awk '{print $2}'
      - cat /etc/netplan/50-cloud-init.yaml
      - IP = "1.2.3.4"
      - echo $IP
      - IP2=$(ip a | grep "inet " | awk '{print $2}')
      - echo $IP
      - export VM_PROFILE="{\"vm_ip\": \"$(echo $IP)\"}"
      - echo $VM_PROFILE
      # - python3 -u deploy.py create_travisci_multinode --VM_PROFILE 
