os: linux
dist: bionic
arch: amd64
before_install:
    - sudo apt-get update
    - sudo apt-get install -y ssh qemu-system-x86 qemu-utils
    - sudo usermod -aG kvm $(whoami)
    - sudo modprobe kvm_intel
    - sudo reboot
language: python
python:
    - "3.6"
install:
    - pip install transient

stages:
    - pre-deploy
    - deploy
    - post-deploy

jobs:
    include:
        - stage: pre-deploy
          script:
              - lsmod |grep kvm
              - pip list |grep trans
              - sudo ifconfig -a
              - sudo ip addr
              - cat /etc/issue
              - uname -a
              - hostname
              - hostname -i
              - sg kvm -c transient run -ssh-console -image centos/7:2004.01 -- -enable-kvm -m 1G <<EOS
            "uname -a"
            EOS
    - stage: deploy
      script:
              - lsmod |grep kvm
              - pip list |grep trans
