os: linux
dist: bionic
arch: amd64
language: python
python:
    - "3.6"
before_install:
    - uname -a
install:
    - uname -a
jobs:
  include:
    - script: source all_in_one_maas_vm_deployment.sh
    #name: "Deploy MaaS"
    - script: source all_in_one_vm_openstack_deployment.sh
    #name: "Deploy OpenStack"
