# This is a basic workflow to help you get started with Actions

name: Osias

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ubuntu-18-deploy-openstack:
    runs-on: ubuntu-18.04
    env:
      PYTHON_VERSION = "3.6"
      TEMPEST_VERSION = "27.0.0"
      REFSTACK_TEST_VERSION = "2020.11"
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["ussuri"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh 

  Ubuntu-20-deploy-openstack:
    runs-on: ubuntu-18.04
    env:
      PYTHON_VERSION = "3.8"
      TEMPEST_VERSION = "27.0.0"
      REFSTACK_TEST_VERSION = "2020.11"
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["ussuri"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh
