name: Osias

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ubuntu-18-deploy-openstack:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["ussuri"]
    env:
      OPENSTACK_RELEASE: ${{ matrix.OPENSTACK_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh ${{ env.OPENSTACK_RELEASE }}
  Ubuntu-20-deploy-openstack:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["wallaby"]
    env:
      OPENSTACK_RELEASE: ${{ matrix.OPENSTACK_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh ${{ env.OPENSTACK_RELEASE }}
