name: Osias

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ubuntu-18-deploy-openstack:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["ussuri"]
    env:
      MAAS_VM_DISTRO: "bionic hwe_kernel=hwe-18.04"
      PYTHON_VERSION: "3.6"
      TEMPEST_VERSION: "27.0.0"
      REFSTACK_TEST_VERSION: "2020.11"
      OPENSTACK_RELEASE: ${{ matrix.OPENSTACK_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh ${{ env.PYTHON_VERSION }} ${{ env.TEMPEST_VERSION }} ${{ env.MAAS_VM_DISTRO }} ${{ env.OPENSTACK_RELEASE }}
  Ubuntu-20-deploy-openstack:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        OPENSTACK_RELEASE: ["wallaby"]
    env:
      MAAS_VM_DISTRO: "focal hwe_kernel=hwe-20.04"
      PYTHON_VERSION: "3.8"
      TEMPEST_VERSION: "27.0.0"
      REFSTACK_TEST_VERSION: "2020.11"
      OPENSTACK_RELEASE: ${{ matrix.OPENSTACK_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy OpenStack
        run: |
          source all_in_one_openstack_deployment.sh ${{ env.PYTHON_VERSION }} ${{ env.TEMPEST_VERSION }} ${{ env.MAAS_VM_DISTRO }} ${{ env.OPENSTACK_RELEASE }}
